version: '3.8'
services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9010:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
  postgres:
    image: postgres:latest
    container_name: postgres_queue
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: queue
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
volumes:
  minio_data: