spring:
  application:
    name: pdQueue
  datasource:
    username: admin
    password: admin
#    url: jdbc:postgresql://192.168.50.86:5432/queue
    url: jdbc:postgresql://localhost:5432/queue
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
minio:
#  url: http://192.168.50.86:9010
  url: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: test